name: Android CI with SonarCloud

on:
  push:
    branches:
      [develop, master]
  pull_request:
    branches:
      [develop, master]

jobs:
  build:
    name: Build, Test & SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Give Gradle wrapper permissions
        run: chmod +x gradlew

      - name: Run tests
        if: github.ref == 'refs/heads/master'
        run: ./gradlew test

      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed for PR analysis
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Add this in your repo settings
        run: |
          ./gradlew sonarqube -Dsonar.projectKey=TopSeriesApp \
                              -Dsonar.organization=davigo2411 \
                              -Dsonar.host.url=https://sonarcloud.io \
                              -Dsonar.login=$SONAR_TOKEN \
