name: Android CI with SonarCloud

on:
  push:
    branches:
      [develop, master]
  pull_request:
    branches:
      [develop, master]

jobs:
  build:
    name: Build, Test & SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests with coverage
        run: ./gradlew clean testDebugUnitTest jacocoTestReport

      - name: Upload JaCoCo Report (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: app/build/reports/jacoco/jacocoTestReport/html

      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed for PR analysis
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Add this in your repo settings
        run: ./gradlew sonarqube \
          -Dsonar.projectKey=TopSeriesApp \
          -Dsonar.organization=davigo2411 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN
          -Dsonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
